### ISSUE TITLE
alert not showing

### ISSUE THREAD

**Issue by football-fastball** [bendc/sprint#9]
Nice library indeed!
Just noticed this issue, the code below is not showing the alert as its should show the alert from the function of the click event of the button.

``` javascript
$(document).ready(function() {
      $( 'body' ).append( "<input type='button' id='alertdiv' value='Text of Alert Button' style='cursor:pointer' />" );
      $('#alertdiv').click(function() {alert("Hello, world!");});
});
```

**Comment by pablomayobre** [comment]
I think this wouldnt work with jQuery either, since the `#alertdiv` element may not be ready when you try to apply the click handler, try doing something like:

``` javascript
$(document).ready(function() {
      $('body').append("<input type='button' id='alertdiv' value='Text of Alert Button' style='cursor:pointer' />");
      $('body').click(function(event) {
            if ($(event.target).is('#alertdiv')){
                  alert("Hello, world!");
            }
      });
});
```

Since `body` will be ready on `document.ready` you can attach handlers to it, if `onclick` is triggered, it will change if the `event.target` is the `alertdiv` button, and if it is make an alert pop-up

PS: In jQuery you have the advantage with the selector attribute for `on` so you could do it with a simpler code:

``` javascript
$(document).ready(function() {
      $('body').append("<input type='button' id='alertdiv' value='Text of Alert Button' style='cursor:pointer' />");
      $('body').on('click', '#alertdiv', function(event) {
            alert("Hello, world!");
      });
});
```

**Comment by football-fastball** [comment]
I have tested that jQuery 2.1.3 does run both your code examples as well as the example I provided.

**Comment by albatros2ko** [comment]
Isn't there a `.trigger(...)` function? Why use `.click(...)`?

This one works for me (tested on both Chrome and Firefox). And `.click(..);` isn't defined or at least, implemented yet.

``` js
$(document).ready(function () {
  $("body").append('<input id="alertdiv" type="button" value="Text of Alert Button" style="cursor:pointer" />');
  $("#alertdiv").on("click", function () { alert("Hello!"); });
});
```

**Comment by bendc** [comment]
@vkeusebio is right, Sprint doesn't support shorthand methods like `.click()`, you should use the generic `.on()` instead.
